add solution for 03-01 button
js-tasks-ru/htmlcss-20220120_vyacheslav-dyomin pull request #3
Opened 2022-01-25 13:27 UTC by v-dyomin

2022-01-25 13:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-25 21:59 UTC, GSemikozov requested changes

2022-01-25 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 100%;
кнопка это такой элемент у которого лучше пусть ширина определяется его внутренним содержимым, если же надо будет растянуть -  тогда уже через модификатор, например .button_full_width

2022-01-25 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает font-family

2022-01-25 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
пожалуй, можно заменить на pointer-events: none

2022-01-25 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
pointer пусть будет по умолчанию на .button

2022-01-25 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled:hover {
у disabled ховера не будет, пользователь не должен взаимодействовать с disabled элементом

2022-01-25 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.demo {
здесь и ниже - определять сторонние блоки и его элементы в файле другого блока нельзя, + если это просто вспомогательные стили чтобы раскидать кнопки, и они нигде реально не будут переиспользоваться - можно задавать прямо в хтмл в тег style

2022-01-26 08:27 UTC, v-dyomin commented on 03-lection1/01-button/button.css
> +    width: 100%;
fixed

2022-01-26 08:30 UTC, v-dyomin commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
в файлике main.css есть такая строка 

`* {
    font-family: 'Roboto', sans-serif;
}`

к к нопкам применяется шрифт Roboto, именной такой шрифт указан для кнопок в figma. Лучше дропнуть єту строку и определить отдельно для кнопок?

2022-01-26 08:32 UTC, v-dyomin commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
fixed

2022-01-26 08:32 UTC, v-dyomin commented on 03-lection1/01-button/button.css
> +.button_primary:disabled:hover {
fixed

2022-01-26 08:34 UTC, v-dyomin commented on 03-lection1/01-button/button.css
> +.demo {
понял
fixed

2022-01-26 08:34 UTC, v-dyomin commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
fixed

2022-01-26 08:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-27 08:32 UTC, v-dyomin commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
fixed

2022-01-27 08:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-27 21:37 UTC, GSemikozov approved these changes

2022-01-27 21:37 UTC, merged